name: Build and Test Wheel

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      wheel_name: ${{ steps.set_wheel_name.outputs.wheel_name }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Build wheel
      run: |
        pip install -r requirements.txt 
        python setup.py bdist_wheel

    - name: Get wheel name
      id: set_wheel_name
      run: echo "::set-output name=wheel_name::$(ls dist/*.whl)"

    - uses: actions/upload-artifact@v2
      with:
        name: wheel-artifact
        path: dist/*.whl

  test:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Download wheel
      uses: actions/download-artifact@v2
      with:
        name: wheel-artifact

    - name: List artifacts (for testing)
      run: ls 

    - name: Install wheel
      run: pip install Lib3MF-2.3.0-py3-none-any.whl

    - name: Run tests
      run: |
        # Replace this with your test script
        python test_lib3mf.py